import { AudienceOption } from "./audiences";

export const genres : Array<AudienceOption> = [
    { label: "Action", value: "urn:tag:genre:media:action" },
    { label: "Adventure", value: "urn:tag:genre:media:adventure" },
    { label: "Animation", value: "urn:tag:genre:media:animation" },
    { label: "Comedy", value: "urn:tag:genre:media:comedy"},
    { label: "Crime", value: "urn:tag:genre:media:crime" },
    { label: "Documentary", value: "urn:tag:genre:media:documentary" },
    { label: "Drama", value: "urn:tag:genre:media:drama" },
    { label: "Family", value: "urn:tag:genre:media:family" },
    { label: "Fantasy", value: "urn:tag:genre:media:fantasy" },
    { label: "History", value: "urn:tag:genre:media:history" },
    { label: "Horror", value: "urn:tag:genre:media:horror" },
    { label: "Music", value: "urn:tag:genre:media:music" },
    { label: "Mystery", value: "urn:tag:genre:media:mystery" },
    { label: "Romance", value: "urn:tag:genre:media:romance" },
    { label: "Science Fiction", value: "urn:tag:genre:media:science_fiction" },
    { label: "Thriller", value: "urn:tag:genre:media:thriller" },
    { label: "War", value: "urn:tag:genre:media:war" },
    { label: "Western", value: "urn:tag:genre:media:western" },
    { label: "Biography", value: "urn:tag:genre:media:biography" },
    { label: "Musical", value: "urn:tag:genre:media:musical" },
    { label: "Sport", value: "urn:tag:genre:media:sport" },
    { label: "Anime", value: "urn:tag:genre:media:anime" },
    { label: "Noir", value: "urn:tag:genre:media:noir" },
    { label: "Medical", value: "urn:tag:genre:media:medical" },
    { label: "Post-Apocalyptic", value: "urn:tag:genre:media:post_apocalyptic" },
    { label: "Cyberpunk", value: "urn:tag:genre:media:cyberpunk" },
    { label: "Steampunk", value: "urn:tag:genre:media:steampunk" },
    { label: "Supernatural", value: "urn:tag:genre:media:supernatural" },
    { label: "Martial Arts", value: "urn:tag:genre:media:martial_arts" },
    { label: "Suspense", value: "urn:tag:genre:media:suspense" },
    { label: "Teen", value: "urn:tag:genre:media:teen" },
    { label: "Travel", value: "urn:tag:genre:media:travel" },
    { label: "Holiday", value: "urn:tag:genre:media:holiday" },
    { label: "Game Show", value: "urn:tag:genre:media:game_show" },
    { label: "Talk Show", value: "urn:tag:genre:media:talk_show" },
    { label: "Kids", value: "urn:tag:genre:media:kids" },
    { label: "Food", value: "urn:tag:genre:media:food" },
    { label: "Nature", value: "urn:tag:genre:media:nature" },
    { label: "Historical Fiction", value: "urn:tag:genre:media:historical_fiction" },
    { label: "Adult", value: "urn:tag:genre:media:adult" },
]