import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar/NavBar";
import { AuthProvider } from "@/providers/AuthContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>
          <div className="gap-16 bg-background min-h-screen font-[family-name:var(--font-inter)]">
            <div>
              <NavBar />
              {children}
            </div>
            <footer className="flex flex-wrap justify-center items-center gap-[24px] row-start-3"></footer>
          </div>
        </AuthProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
